[battery]
disabled = true

[kubernetes]
disabled = false
contexts = [
    { context_pattern = '(?P<var_cluster>\w+)\.\w+\.\w+\.\w+', context_alias = '$var_cluster' },
    { context_pattern = 'gke_[a-z0-9-]+_[a-z0-9-]+_(?P<var_cluster>[\w-]+)', context_alias = '$var_cluster' },
]

[aws]
disabled = true

[time]
disabled = false
format = '[$time]($style) '

[pulumi]
disabled = true

[localip]
disabled = true

[direnv]
disabled = false
# The default is "bold orange" however no such ANSI color exists.
# Use the hexadecimal RGB code for orange from here:
# https://github.com/jan-warchol/selenized/blob/master/the-values.md#selenized-black
style = 'bold #e67f43'
